- hosts: localhost
  connection: local
  gather_facts: False
  tasks: 
    - name: Import VPC variables
      include_vars: Vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{state}}"
      register: VpcOut
    - debug:
        var: VpcOut

    - name: Create public Subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{VpcOut.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: present
        map_public: true
        tags:
          Name: Vprofile-pubsub1
      register: vpc_pubsub1
